### ISSUE TITLE
XML Parsing Error: not well-formed

### ISSUE THREAD

**Issue by unickq** [jenkinsci/junit-plugin#252]
Hi, is there a way to ignore not well-formed xmls?

```
Failed to read test report file C:\jenkins\workspace\run-tests-ui_qa\test-results\wdio\junit-reports\wdio-0-47.xml
org.dom4j.DocumentException: Error on line 409 of document  : An invalid XML character (Unicode: 0x1b) was found in the value of attribute "message" and element is "error".
	at org.dom4j.io.SAXReader.read(SAXReader.java:511)
	at org.dom4j.io.SAXReader.read(SAXReader.java:392)
	at hudson.tasks.junit.SuiteResult.parse(SuiteResult.java:178)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:378)
	at hudson.tasks.junit.TestResult.parsePossiblyEmpty(TestResult.java:308)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:224)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:196)
	at hudson.tasks.junit.TestResult.<init>(TestResult.java:151)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:144)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3314)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:376)
	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:119)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.xml.sax.SAXParseException; lineNumber: 409; columnNumber: 23; An invalid XML character (Unicode: 0x1b) was found in the value of attribute "message" and element is "error".
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
```

and this is an XML line 407-409

```xml
<testcase classname="chrome.88_0_4324_182.windows.Validate_paid_item_is_stored_in_saved_drafts_and_purchases" name="Validate_drafts_contain_paid_item" time="1.841" file=".\tests\web\desktop\premium\invitation\purchase.memberTab.spec.ts">
      <error message="[2mexpect([22m[31mreceived[39m[2m).[22mtoBe[2m([22m[32mexpected[39m[2m) // Object.is equality[22m&#xA;&#xA;Expected: [32m1[39m&#xA;Received: [31m0[39m"/>
      <system-out>
```

**Comment by unickq** [comment]
Jenkins 2.280, JUnit plugin 1.48

**Comment by unickq** [comment]
Not an issue of junit - https://github.com/webdriverio/webdriverio/issues/6358
