### ISSUE TITLE
NullPointerException when a new test fails.

### ISSUE THREAD

**Issue by StefanCardnellVOSS** [jenkinsci/junit-plugin#397]
### Brief

I am seeing an issue on our live system where NullPointerException occurs when a test fails for the first time. I have reduced it to a minimal example below.

### Jenkins and plugins versions report

Jenkins: 2.332.1
OS: Linux - 4.15.0-175-generic
junit:1.57

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 16.04

### Reproduction steps

1. Create a pipeline with the following script:

```
pipeline {
    agent any
    stages {
        stage('XML Stage') {
            steps {
                echo 'Start XML stage'
                writeXML()
                archiveArtifacts artifacts: '*.xml'
            }
        }
        stage('Publish results') {
            steps {
                junit healthScaleFactor: 5.0, testResults: "result.xml"
            }
        }
    }
}

def writeXML() {
    writeFile encoding: 'UTF-8', file: 'result.xml', text: '''<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="2582.5670" tests="1" failures="0">
  <testsuite name="Root Suite.succeeds" timestamp="2022-05-19T12:20:04" tests="1" time="0.0070" failures="0">
    <testcase name="should not be empty" time="0.0010" classname="succeeds">
    </testcase>
  </testsuite>
</testsuites>'''
}
```

This mocks up an XML with a single test case which succeeds. Note the class name of the `<testcase>` is _succeeds_.

2. Run this pipeline, expect a green build.

3. Now replace `writeXML` above with the following:

```
def writeXML() {
    writeFile encoding: 'UTF-8', file: 'result.xml', text: '''<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="2582.5670" tests="1" failures="1">
  <testsuite name="Root Suite.fails" timestamp="2022-05-19T12:20:04" tests="3" time="0.0070" failures="1">
    <testcase name="should not be empty" time="0.0010" classname="fails">
        <failure message="expected &apos;A&apos; to equal &apos;B&apos;" type="AssertionError"></failure>
    </testcase>
  </testsuite>
</testsuites>'''
}
```

In this case, we add a failure case _**and importantly**_ we change the class name of the `<testcase>` from _succeeds_ to _fails_. This can happen real-world as tests are added or removed to our test suite.

4. Run the pipeline.

### Expected Results

Should run fine, not a green build but an amber build with a JUnit test result.

### Actual Results

An exception is produced by the JUnit plugin with the following exception:

```
Recording test results
null
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
java.lang.NullPointerException
	at hudson.tasks.junit.TestResult.getCase(TestResult.java:931)
	at hudson.tasks.junit.CaseResult.getPreviousResult(CaseResult.java:540)
	at hudson.tasks.junit.CaseResult.recomputeFailedSinceIfNeeded(CaseResult.java:453)
	at hudson.tasks.junit.CaseResult.freeze(CaseResult.java:704)
	at hudson.tasks.junit.SuiteResult.freeze(SuiteResult.java:454)
	at hudson.tasks.junit.TestResult.freeze(TestResult.java:825)
	at hudson.tasks.junit.TestResultAction.setResult(TestResultAction.java:115)
	at hudson.tasks.junit.TestResultAction.<init>(TestResultAction.java:90)
	at hudson.tasks.junit.JUnitResultArchiver.parseAndSummarize(JUnitResultArchiver.java:260)
	at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:63)
	at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:29)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Finished: FAILURE
```

It seems that JUnit fails when trying to retrieve previous test results for a failed case. Probably because the failure is for a new test, it can't retrieve previous results and bombs out - this shouldn't really be the case.

I can see in the following commit a lot of changes were made to how previous case results were retrieved:

https://github.com/jenkinsci/junit-plugin/commit/b4fdc2dbfb444346142acbcdf89e28fd68ceff54

Since this was commit was 31st March it makes sense why I've only been seeing this issue recently.

**Comment by timja** [comment]
Cc @Vlatombe

**Comment by StefanCardnellVOSS** [comment]
Apologies all, I just tried this on the latest version 1119.va_a_5e9068da_d7 and can't reproduce the issue. Should've checked that first!
