### ISSUE TITLE
Publish Junit Report throws java.io.FileNotFoundException: /opt/jdk/openJDK8/jre/lib/resources.jar

### ISSUE THREAD

**Issue by sharatsathyanarayan** [jenkinsci/junit-plugin#508]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
Jenkins 2.332.3 Debian OS 11
OPENJDK8
JUnit Version1119.1121.vc43d0fc45561

  ```text
  13:28:56 [INFO] ------------------------------------------------------------------------
13:28:56 [INFO] BUILD SUCCESS
13:28:56 [INFO] ------------------------------------------------------------------------
13:28:56 [INFO] Total time: 01:35 min
13:28:56 [INFO] Finished at: 2023-03-22T20:28:56+00:00
13:28:56 [INFO] Final Memory: 226M/2656M
13:28:57 [INFO] ------------------------------------------------------------------------
13:28:57 Recording test results
13:28:57 ERROR: Step ?Publish JUnit test result report? aborted due to exception: 
13:28:59 java.io.FileNotFoundException: /opt/jdk/openJDK8/jre/lib/resources.jar
13:28:59 	at sun.misc.URLClassPath$JarLoader.getJarFile(URLClassPath.java:938)
13:28:59 	at sun.misc.URLClassPath$JarLoader.access$800(URLClassPath.java:801)
13:28:59 	at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:886)
13:28:59 	at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:879)
13:28:59 	at java.security.AccessController.doPrivileged(Native Method)
13:28:59 	at sun.misc.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:878)
13:28:59 	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1050)
13:28:59 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

DEBIAN OS 11

### Reproduction steps

This started happening all of a sudden! I am not sure why either

### Expected Results

JUNIT results to be published

### Actual Results

I dont know why JUNIT plugin needs resources.jar "/opt/jdk/openJDK8/jre/lib/resources.jar"

**Comment by sharatsathyanarayan** [comment]
Not plugin issue
