### ISSUE TITLE
Recent refactoring broke test stability history plugin

### ISSUE THREAD

**Issue by Bananeweizen** [jenkinsci/junit-plugin#627]
### Jenkins and plugins versions report

n.a

### What Operating System are you using (both controller, and any agents involved in the problem)?

n.a

### Reproduction steps

Install https://plugins.jenkins.io/test-stability/
Upgrade junit-plugin

### Expected Results

no errors

### Actual Results

java.lang.NoSuchMethodError: 'java.util.List hudson.tasks.junit.ClassResult.getChildren()'
	at PluginClassLoader for test-stability//de.esailors.jenkins.teststability.StabilityTestDataPublisher.getClassAndCaseResults(StabilityTestDataPublisher.java:274)
	at PluginClassLoader for test-stability//de.esailors.jenkins.teststability.StabilityTestDataPublisher.contributeTestData(StabilityTestDataPublisher.java:76)
	at PluginClassLoader for junit//hudson.tasks.junit.JUnitResultArchiver.parseAndSummarize(JUnitResultArchiver.java:297)
	at PluginClassLoader for junit//hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:63)
	at PluginClassLoader for junit//hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:29)
	at PluginClassLoader for workflow-step-api//org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

### Anything else?

Root cause is the generalization of the generic method return value at https://github.com/jenkinsci/junit-plugin/commit/72cf99b25c43c25d923ee5e2f9a37cc036f32a0b#r144682183

### Are you interested in contributing a fix?

no

**Comment by timja** [comment]
Can you try this pre-release version of test-stability please: https://repo.jenkins-ci.org/incrementals/de/esailors/jenkins/test-stability/2.4-rc57.d8c750ea_292e/test-stability-2.4-rc57.d8c750ea_292e.hpi

**Comment by ivy-cst** [comment]
> Can you try this pre-release version of test-stability please: https://repo.jenkins-ci.org/incrementals/de/esailors/jenkins/test-stability/2.4-rc57.d8c750ea_292e/test-stability-2.4-rc57.d8c750ea_292e.hpi
With this pre-release it works, thanks :+1:

**Comment by timja** [comment]
Released in https://github.com/jenkinsci/test-stability-plugin/releases/tag/test-stability-2.4
